version: "3.9"

services:
  database:
    container_name: postgres-db
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: astro-db
    expose:
      - "5432"

  admin_panel:
    container_name: admin_panel
    image: fastapi-admin-panel:1.0.4
    restart: on-failure
    build:
      context: ..
      dockerfile: deploy/application.Dockerfile
    environment:
      APPLICATION_HOST: 0.0.0.0
      APPLICATION_PORT: 5000
      AMOUNT_OF_GUNICORN_WORKERS: 1
      APP_LOCATION: "bootstrap:app"
    privileged: false
    depends_on: [ database ]
    expose:
      - "5000"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ../fastapi_admin/templates:/static
    depends_on:
      - admin_panel


volumes:
  staticfiles:
